# Site settings
title: Coaching Concept 3D
title-part1: Coaching
title-part2: Concept 3D
slogan: Votre premier pas vers votre objectif
email: coachingconcept3d@gmail.com
url: http://www.coaching-concept3d.be
description: ""

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2A738B #80B3FF
  secondary: 16A3A9 #FD6E8A
  secondary-dark: 8F8F8F #A2122F

# Footer settings
footer:
  copyright: Coaching Concept 3D
  location: Adresse
  social: Réseaux Sociaux
  credits: Crédits
  links: Liens

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/pages/Coaching-Concept-3D/505663926253688

# Postal address (add as many lines as necessary)
address:
  - line: 20 Rue Pont Sainte Maxence
  - line: B-5060 Auvelais

links:
  - title: certificate
    description: Mental Coaching Academy
    url: http://www.mentalcoachingacademy.com/

# Credits content
credits: ''

# Build settings
markdown: kramdown
permalink: pretty
